### Авторизація та отримання токена
POST http://127.0.0.1:80/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.access);
 %}

### Запит до рекомендацій БЕЗ токена
GET http://127.0.0.1:80/api/recommendations/

### Запит до рекомендацій З валідним токеном
GET http://127.0.0.1:80/api/recommendations/
Authorization: Bearer {{auth_token}}