### Отримання всіх коментарів
GET http://127.0.0.1:80/api/comments/
Authorization: Bearer {{auth_token}}

### Створення коментаря
POST http://127.0.0.1:80/api/comments/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "post": 6,
  "text": "Просто коментар"
}

### Редагування коментаря
PATCH http://127.0.0.1:80/api/comments/1/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "text": ""
}

### Видалення коментаря
DELETE http://127.0.0.1:80/api/comments/1/
Authorization: Bearer {{auth_token}}