# Generated by Django 6.0.2 on 2026-02-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='lat_modified',
            new_name='last_modified',
        ),
    ]
